"""Derive a next-word suggestion table from McBopomofo phrase occurrence data.

Each phrase such as 今天晚上 contributes its continuation to every short prefix:
今 -> 天 (phrase is at most two characters longer than the prefix), 今天 -> 晚上.
Counts are summed per prefix and only the most frequent continuations are kept.

Usage (repository root):
    python tools/build_next_word_table.py          # regenerate the asset
    python tools/build_next_word_table.py --check  # fail if the asset is stale
"""

import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "tools" / "data" / "mcbopomofo_phrase.occ"
TARGET = ROOT / "app" / "src" / "main" / "assets" / "next_word.tsv"

MAX_PREFIX = 3
MAX_CONTINUATION = 2
PER_PREFIX = 8
MIN_COUNT = 3


def is_han(text: str) -> bool:
    return bool(text) and all("㐀" <= ch <= "鿿" for ch in text)


def build() -> str:
    counts: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))
    for line in SOURCE.read_text(encoding="utf-8").splitlines():
        phrase, _, raw = line.partition(" ")
        if len(phrase) < 2 or not is_han(phrase) or not raw.strip().isdigit():
            continue
        occurrences = int(raw)
        for size in range(1, min(MAX_PREFIX, len(phrase) - 1) + 1):
            rest = phrase[size:]
            if len(rest) <= MAX_CONTINUATION:
                counts[phrase[:size]][rest] += occurrences

    rows = []
    for prefix in sorted(counts):
        ranked = sorted(
            ((word, n) for word, n in counts[prefix].items() if n >= MIN_COUNT),
            key=lambda item: (-item[1], item[0]),
        )[:PER_PREFIX]
        if ranked:
            rows.append(f"{prefix}\t{' '.join(word for word, _ in ranked)}")

    header = [
        "# Next-word suggestions derived from McBopomofo phrase.occ (MIT License)",
        "# Generated by tools/build_next_word_table.py; do not edit by hand.",
        "# prefix<TAB>continuation1 continuation2 ...",
    ]
    return "\n".join(header + rows) + "\n"


def main() -> None:
    generated = build()
    if "--check" in sys.argv:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != generated:
            raise SystemExit(f"{TARGET} is stale; run tools/build_next_word_table.py")
        print("next_word.tsv is up to date")
        return
    TARGET.write_text(generated, encoding="utf-8", newline="\n")
    print(f"wrote {TARGET} ({len(generated.splitlines()) - 3} prefixes, {len(generated.encode('utf-8'))} bytes)")


if __name__ == "__main__":
    main()
